config/routes.rb
PestControl::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :bugs
  
  root to: 'bugs#index'
  

  match '/signup',   to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete
  match '/reportbug', to: 'bugs#new'
  
  match '/help',  to: 'static_pages#help'
  match '/about',    to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'  
  
  
     

end

app/models/bug.rb
class Bug < ActiveRecord::Base
   attr_accessible :title, :description, :status, :priority, :reported_by, :closed_by, :comment, :screenshot, :image_file_name, :image_content_type, :image_file_size, :image_updated_at
   has_attached_file :screenshot,
                     :url => "/assets/images/screenshots/:attachment/:id/:style/:basename.:extension",
                     :path => ":rails_root/public/assets/images/screenshots/:attachment/:id/:style/:basename.:extension"
   
   validates :title,  presence: true
   validates :status,  presence: true
   
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :name, :email, :password, :password_confirmation, :admin
   has_secure_password
   has_many :bugs
  
   before_save { self.email.downcase! }  
   before_save :create_remember_token

   validates :name,  presence: true, length: { maximum: 50 }
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

   validates :password, presence: true, length: { minimum: 6 }
   validates :password_confirmation, presence: true
  
   private
      def create_remember_token
         self.remember_token = SecureRandom.urlsafe_base64
      end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  include BugsHelper

end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController

  def index
     if signed_in? == false
        redirect_to signin_path
     else
       if params[:commit] == "Show all"
          params[:q].each { |key, value| params[:q][key] = "" }
       end
       @search = Bug.search(params[:q])
       @bugs = @search.result.paginate(page: params[:page], :per_page => 12)
   
       respond_to do |format|
         format.html # index.html.erb
         format.json { render json: @bugs }
       end        
     end
     
  end

  def show
    @bug = Bug.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bug }
    end
  end

  def new
    @bug = Bug.new
  end

  def edit
    @bug = Bug.find(params[:id])
    # @bug.priority = priority_to_str(@bug.priority)
  end

  def create
    #params[:bug][:priority] = priority_to_int(params[:bug][:priority])
    @bug = Bug.new(params[:bug])
    @bug.reported_by = current_user.id

    if @bug.save
      flash[:success] = "Bug reported."
      redirect_to @bug
    else
      render 'new'
    end
  end
  
  def update   
    @bug = Bug.find(params[:id])

    if @bug.update_attributes(params[:bug])
       flash[:success] = "Bug updated."
       redirect_to @bug
    else
       render 'new'
    end
  end

  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy
    flash[:success] = "Bug deleted."

    respond_to do |format|
      format.html { redirect_to bugs_url }
      format.json { head :no_content }
      format.js { redirect_to root_path }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   
   def new      
      flash[:welcome] = "Welcome to Pest Control! Visit the 'About' page 
                        for an intro to the app. 
                         Guests may log in using: 'guest@guest.com' and 'password'"
   end
   
   def create
      user = User.find_by_email(params[:session][:email])
      if user && user.authenticate(params[:session][:password])
         sign_in user
         redirect_to root_path
      else
         flash.now[:error] = 'Invalid email/password combination'
         render 'new'
      end
   end
     
   def destroy
      sign_out
      redirect_to signin_path
   end
   
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  def index
     @users = User.all     
  end
  
  def show
     @user = User.find(params[:id])
  end
  
  def new
     @user = User.new
  end

  def edit
     @user = User.find(params[:id])     
  end
  
  def update
      if @user.update_attributes(params[:user])
         flash[:success] = "Profile updated."
         sign_in @user
         redirect_to @user
      else
         render 'edit'
      end   
  end
  
  def create
     @user = User.new(params[:user])
     if @user.save
        sign_in @user
        flash[:success] = "Account created. Welcome to Pest Control!"
        redirect_to root_path
     else
        render 'new'
     end
  end
   

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
   
   def creator_name (id)
      User.find_by_id(id).name
   end
   
   def priority_to_int(str)
      case str
         when 'Urgent'
           return_int = 0
         when 'High'
           return_int = 1
         when 'Medium'
           return_int = 2        
         else
           return_int = 3  
      end        
      return_int     
   end
   
   def priority_to_str(int)
      case int
         when 0
           return_str = 'Urgent'
         when 1
           return_str = 'High'
         when 2
           return_str = 'Medium'      
         else
           return_str = 'Low'
      end        
      return_str       
   end
end

app/helpers/sessions_helper.rb
module SessionsHelper
   
   
   def sign_in(user)
      cookies.permanent[:remember_token] = user.remember_token
      self.current_user = user
   end
   
   def signed_in?
      !current_user.nil?
   end
   
   def current_user=(user)
      @current_user = user
   end
   
   def current_user
      @current_user ||= User.find_by_remember_token(cookies[:remember_token])
   end
   
   def sign_out
      self.current_user = nil
      cookies.delete(:remember_token)
   end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_form.html.erb
<div class="row bug_form">
	<div class="span6 offset3">

		<%= form_for(@bug) do |f| %>
			<%= render 'shared/error_messages', {:object => f.object, :multipart => true} %>
		
		    <%= f.label :title %><br />
		    <%= f.text_field :title %>
		
		    <%= f.label :description %><br />
		    <%= f.text_area :description %>
		
		    <%= f.label :status %><br />
		    <%= f.text_field :status %>
		
		    <%= f.label :priority %><br />
		    <%= f.select :priority, [['Urgent',0],['High',1],['Medium',2],['Low',3]] %>
		
		    <%= f.label :closed_by %><br />
		    <%= f.text_field :closed_by %>
		
		    <%= f.label :comment %><br />
		    <%= f.text_area :comment %>
		    
			<%= f.file_field :screenshot %>
			<%= f.submit "Submit bug report", class: "btn btn-large btn-primary" %>

		<% end %>
	</div>
</div>

app/views/bugs/edit.html.erb
<%= provide(:title, 'Edit bug report') %>

<h1>Editing bug</h1>

<%= render 'form' %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/index.html.erb
<%= provide(:title, 'Reported bugs') %>

<h1>'HUD Maps' bugs</h1>

<form method="get" action="/reportbug">
    <button type="submit" class="btn btn-primary">Report a bug</button>
</form>

<%= search_form_for @search do |f| %>
	<div class="search_form">
		<div class="search_field">
			<%= f.label :title_cont, "Title contains:" %>
			<%= f.text_field :title_cont %>
		</div>
		<div class="search_field">
			<%= f.label :status_cont, "Status:" %>
			<%= f.text_field :status_cont %>
		</div>
		<div class="search_field">
			<%= f.label :description_cont, "Description contains:" %>
			<%= f.text_field :description_cont %>
		</div>				
		<div class="search_btn">
			<%= f.submit "Search" %>
			<%= f.submit "Show all" %>
		</div>
	</div>
<% end %>

<table class="bug_table">
  <tr>
    <th><%= sort_link @search, :title, "Title" %></th>
    <th><%= sort_link @search, :status, "Status" %></th>
    <th><%= sort_link @search, :priority, "Priority" %></th>
    <th><%= sort_link @search, :created_at, "Created at" %></th>
    <th><%= sort_link @search, :reported_by, "Reported by" %></th>                  
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bugs.each do |bug| %>
  <tr class="fade-bug-row">
    <td><%= truncate(bug.title, length: 30, separator: ' ') %></td>
    <td><%= bug.status %></td>
    <td <% if bug.priority == 0 %> class="urgent-red" <% end %> >
    	<%= priority_to_str(bug.priority) %>
    </td>
    <td><%= bug.created_at.to_formatted_s(:short) %></td>  
    <td><%= creator_name(bug.reported_by) %></td>   
    <td><%= link_to 'View', bug %></td>
    <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
    <td><%= link_to 'Delete', bug, method: :delete,
    							   remote: true, 
    							   data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= will_paginate %>

app/views/bugs/new.html.erb
<%= provide(:title, 'Report a bug') %>

<h1>Report a bug</h1>

<%= render 'form' %>

app/views/bugs/show.html.erb
<div class="bug-show">

	<%#= Heroku-necessitated hack for portfolio version, in lieu of test for @bug.screenshot %>
	<div class="screenshot">
		<%= image_tag("http://www.johnkanthak.com/portfolio/assets/fake_screenshot.png") %>	
	</div>

		
	<p>
	  <b>Title:</b>
	  <%= @bug.title %>
	</p>
	
	<p>
	  <b>Description:</b>
	  <%= @bug.description %>
	</p>
	
	<p>
	  <b>Priority:</b>
	  <%= priority_to_str(@bug.priority) %>
	</p>
	
	<p>
	  <b>Status:</b>
	  <%= @bug.status %>
	</p>
	
	<p>
	  <b>Closed by:</b>
	  <%= @bug.closed_by %>
	</p>
	
	<p>
	  <b>Comment:</b>
	  <%= @bug.comment %>
	</p>
	
	
	<%= link_to 'Edit', edit_bug_path(@bug) %> |
	<%= link_to 'Back', bugs_path %>
	
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to image_tag("pest_control.png", alt: "Pest Control", class: "bug-logo"), root_path %>
			<span id="logo">Pest Control</span>
			<nav>
				<ul class="nav pull-right">					
					<li> <%= link_to "Help",    help_path %> </li>
					<% if signed_in? %>
						<li> <%= link_to "Bug List",    root_path %> </li>
						<% if current_user.admin %>
							<li> <%= link_to "Users",    users_path %> </li>
						<% end %>
						<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
					<% else %>
						<li> <%= link_to "Sign in", signin_path %> </li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pest Control | <%= yield(:title) %></title>
		<%= stylesheet_link_tag    "application", :media => "all" %>		
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<br/><br/><br/><br/><br/><br/>
			<%= debug(params) if Rails.env.development? %>
		</div>			
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<%= provide(:title, 'About') %>

<h1>About Pest Control</h1>
<p>John Kanthak created the Pest Control dedicated 
	bug tracking app in March 2013 for use by the team of IT contractors
	maintaining and upgrading the HUD Maps ArcGIS application
	for the U.S. Dept. of Housing and Urban Development.</p>
<p>That project fell under the Sequester axe shortly thereafter 
	and the team disbanded. Although Pest Control is not currently in
	active use, John maintains it on Heroku for portfolio purposes.</p>
<p>Pest Control uses Ransack for search and sort functionality, Paperclip for 
	image uploading, and modified Twitter Bootstrap for styling. Bug reports 
	are deleted with Ajax and unobtrusive jQuery.
</p>
<p>
	See the source code at: <a href="https://github.com/jkanthak/pest_control.git">https://github.com/jkanthak/pest_control.git</a>
</p>
<p>Enjoy your visit, and email John with any questions
	at: 
	<a href="mailto:johnkanthak@gmail.com?Subject=Pest%20Control">
johnkanthak@gmail.com.</a>
</p>		

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Pest Control administrator John Kanthak at: 
	<a href="mailto:johnkanthak@gmail.com?Subject=Pest%20Control">
johnkanthak@gmail.com.</a>
</p>  

app/views/static_pages/help.html.erb
<%= provide(:title, 'Help') %>

<h1>Help</h1>
<p>We're sorry, but our sources indicate that you are beyond all help.
	We here at Pest Control wish you the best of luck.</p>		
<br />
<p>(Seriously, though, no help page. Info about the app can be found in the 'About' page.)</p>

app/views/static_pages/home.html.erb
<%= provide(:title, 'Pest Control') %>

<h1>Pest Control</h1>
<p>This is the home page for the Pest Control app.</p>		

app/views/users/_form.html.erb
<div class="row bug_form">
	<div class="span4 offset4">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', :object => f.object %>
			
			<%= f.label :name %><br />
			<%= f.text_field :name %>
			
			<%= f.label :email %><br />
			<%= f.text_field :email %>
	
	    	<%= f.label :admin %><br />
 			<%= f.select :admin, [['Yes', true],['No',false]] %>			
			
			<%= f.label :password %><br />
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation, "Confirmation" %><br />
			<%= f.password_field :password_confirmation %>
			
			<%= f.submit "Submit user", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= provide(:title, 'Users') %>

<h1>Pest Control users</h1>

<table class="bug_table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Admin</th>    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.admin %></td>    
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', :object => f.object %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
			
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>
			
			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<h1><%= @user.name %></h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= link_to 'Back', users_path %>